name: Build

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "LICENSE"

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin: spacer
            name: spacer-linux-aarch64.tar.gz
            command: build

          - release_for: macOS aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: spacer
            name: spacer-darwin-aarch64.tar.gz
            command: build

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: spacer-${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/spacer

  # github_build:
  #   name: Build release binaries
  #   strategy:
  #     matrix:
  #       target:
  #         # - x86_64-unknown-linux-gnu
  #         - aarch64-unknown-linux-gnu
  #         # - x86_64-apple-darwin
  #         # - aarch64-apple-darwin
  #       include:
  #         # - target: x86_64-unknown-linux-gnu
  #         #   os: ubuntu-latest
  #         #   name: spacer-x86_64-unknown-linux-gnu.tar.gz
  #         - target: aarch64-unknown-linux-gnu
  #           os: ubuntu-latest
  #           name: spacer-aarch64-unknown-linux-gnu.tar.gz
  #         # - target: x86_64-apple-darwin
  #         #   os: ubuntu-latest
  #         #   name: spacer-x86_64-apple-darwin.tar.gz
  #         - target: aarch64-apple-darwin
  #           os: macOS-latest
  #           name: spacer-aarch64-apple-darwin.tar.gz
  #         # - target: x86_64-pc-windows-msvc
  #         #   os: windows-latest
  #         #   name: spacer-x86_64-pc-windows-msvc.zip
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Install Rust toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true
  #         target: ${{ matrix.target }}

  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: build
  #         args: --release --target ${{ matrix.target }}

  #     - name: Prepare build artifacts [Windows]
  #       if: matrix.os == 'windows-latest'
  #       run: |
  #         cd target/${{ matrix.target }}/release
  #         strip spacer.exe
  #         7z a ../../../${{ matrix.name }} spacer.exe
  #         cd -

  #     - name: Prepare build artifacts [-nix]
  #       if: matrix.os != 'windows-latest'
  #       run: |
  #         cd target/${{ matrix.target }}/release
  #         strip spacer
  #         tar czvf ../../../${{ matrix.name }} spacer
  #         cd -

  #     - name: Upload build artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: ${{ matrix.name }}
  #         path: ${{ matrix.name }}
